import streamlit as st
from pptx import Presentation
st.set_page_config(
    page_title="LongForm AI",
    page_icon="favicon.png",
    layout="wide"
)
from reportlab.pdfgen import canvas
from openai import OpenAI
import os
import base64
from PIL import Image, ImageDraw
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
@st.cache_data
def generate_ai_text(prompt):
    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )
    return response.output_text
st.title("LongForm AI")
st.subheader("AI tools for long-form content")
tool = st.sidebar.selectbox(
    "Choose Tool",
    [
    "Book Generator",
    "Presentation Generator",
    "Pitch Deck Generator",
    "Business Report",
    "Long Text Editor"
    ]
)
def translate_text(text, language):
    prompt = f"""
    Translate the following text to {language}
    Keep formatting, bullet points and paragraphs.
    IMPORTANT:
    - Do NOT summarize
    - Do NOT shorten the text
    - Keep the same structure
    TEXT:
    {text}
    """
    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt

    )

    return response.output_text
def create_pdf(text, cover_image, filename="book.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    cover = ImageReader(cover_image)
    c.drawImage(cover, 0, 0, width=width, height=height)
    c.showPage()
    c.setFont("Helvetica", 18)
    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, height - 320, "Generated by your AI tool")
    c.showPage()
    c.setFont("Helvetica-Bold", 24)
    c.drawString(200, height - 100, "Table of contents")
    c.setFont("Helvetica", 14)
    y_toc = height - 150
    for line in text.split("\n"):
        if line.startwith("chapter"):
            c.drawString(100, y_toc, line)
            y_toc -= 25
    c.showPage()
    c.setFont("Helvetica-Bold", 24)
    c.drawString(180, height - 80, "AI Generated Book")
    c.setFont("Helvetica", 12)
    y = height - 120
    page = 1
    for line in text.split("\n"):
        c.drawString(40, y, line)
        y -= 20
        if y < 40:
            c.drawString( - 100, 20, f"Page {page}")
            page +=1
            c.showPage()
            c.setFont("Helvetica", 12)
            y = height - 40
            c.save()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
def generate_cover(topic, author):

    prompt = f"Professional book cover for a book about {topic}, author: {author}"

    try:
        response = client.images.generate(
            model="gpt-image-1",
            prompt=prompt,
            size="1024x1024"
        )

        image_base64 = response.data[0].b64_json
        image_bytes = base64.b64decode(image_base64)
        image = Image.open(BytesIO(image_bytes))

        draw = ImageDraw.Draw(image)
        width, height = image.size

        draw.text((width/2 - 150, height - 120), topic.upper(), fill="white")
        draw.text((width/2 - 150, height - 60), author.upper(), fill="white")

        return image

    except Exception as e:
        st.error(f"Error generating cover: {e}")
        return None
if tool == "Book Generator":
    st.header("Book Generator")
    topic = st.text_input("Book topic")
    user_text = st.text_area(
        "Optional: Paste notes or text for the book",
        height=250
    )
    author = st.text_input("Author")
    language = st.selectbox(
        "Translate book to:",
        [   "None",
            "English",
            "Norwegian",
            "Persian",
            "Swedish",
            "Arabic",
            "Urdu",
            "Spanish",
            "Hindi",
            "German",
            "Turkish",
            "Italian",
            "Chinese",
            "French",
            "Japanese"
        ]
    )
    chapters = st.slider("Number of chapters", 1, 10, 3)
    topic = st.text_input("Book topic", key="topic_input")
    author = st.text_input("Author", key="author_input")
    if topic and author:
        cover_image = generate_cover(topic, author)
        st.image(cover_image, caption="AI Generated Book Cover")
        st.markdown(f"**Author:** {author}")
        st.markdown("---")
        st.markdown("### Uppgrade to LongForm AI Pro")
        st.link_button(
            "Uppgrade to Pro (§19/month)",
            "https://buy.stripe.com/test_7sY14ocfid2PdjkFd67S00"
        )
    if st.button("Generate Book"):
        st.session_state.book = {}
        book_summary = ""
        outline_prompt = f"""
        Create a detailed outline for a professional book.
        Book topic:
        {topic}
        User material:
        {user_text}
        The book should contain {chapters} chapters.
        For each chapter provide:
        - Chapter number
        - chapter title
        - short description of what the chapter will cover
        """
        outline_response = client.responses.create(
            model="gpt-4.1-mini",
            input=outline_prompt
        )
        outline = outline_response.output_text
        st.markdown("## Book Outline")
        st.write(outline)
        lang_instruction = ""
        progress = st.progress(0)
        status = st.empty()
        book_container = st.empty()
        book = ""
        for i in range(1, chapters+1):
            status.write(f"Writing chapter {i} of {chapters}...")
            prompt = f"""
            Write Chapter {i} of a professional book about {topic}.
            Book outline:
            {outline}
            Focus only on chapter {i} from the outline. 
            The chapter must be very detailed and contain approximately 2500-3000 words.
            Write long, well-developed paragraphs.
            Book summary so far:
            {book_summary}
            Rules:
            - Wite like a real book author
            - Do NOT mention AI
            - Do NOT ask the reader questions
            - Do NOT say things "let me know if you want more"
            - Use clear headings and explainztions
            - include examples when usefull
            {lang_instruction}
            include explanations and examples.
            """
            try:
                chapter_response = client.responses.create(
                    model="gpt-4.1-mini",
                    input=prompt
                )
                chapter_text = chapter_response.output_text
                st.session_state.book[i] = chapter_text
                summary_prompt = f"""
                Summarize the key ideas of this chapter in 5 sentences.
                Chapter text:
                {chapter_text}
                """
                summary_response = client.responses.create(
                    model="gpt-4.1-mini",
                    input=summary_prompt
                )
                chapter_summary = summary_response.output_text
                book_summary += chapter_summary + "\n"
            except Exception as e:
                st.error(f"Error generating chapter: {e}")
                chapter_text = "Chapter generation failed."
                st.session_state.book[i] = chapter_text
            progress.progress(i / chapters)
            summary_prompt = f"""
            Summarize the key ideas from this chapter in 5 sentences.
            Chapter text:
            {chapter_text}
            """
            summary_response = client.responses.create(
                model="gpt-4.1-mini",
                input=summary_prompt
            )
            chapter_summary = summary_response.output_text
            book_summary += chapter_summary + "\n"
    
        if language != "None":
            lang_instruction = f"write the chapter in {language}."
        else:
            lang_instruction = ""
            book = translate_text(book, language)
        edit_status = st.empty()
        edit_status.write("Editing the full book...")
        edit_prompt = f"""
        You are a professional book editor.
        Improve the following book while keeping the same structure.
        Tasks:
        - Improve writing quality
        - Fix grammar
        - Improve flow between chapters
        - Make the book more professionl
        Book:
        {book}
        """
        edit_response = client.responses.create(
            model="gpt-4.1-mini",
            input=edit_prompt 
        )
        edited_book = edit_response.output_text
        edit_status.success("Book editing complete")
        st.markdown(book)
        if st.button("Create PDF"):
            create_pdf(book, cover_image)

        with open("book.pdf", "rb") as f:
            st.download_button(
                "Download PDF Book",
                data=f,
                file_name="book.pdf",
            )
            for i in sorted(st.session_state.book):
                    st.markdown(f"## Chapter {i}")
                    st.write(st.session_state.book[i])
if tool == "Long Text Editor":
    st.header("Long Text Editor")
    text = st.text_area(
        "Paste your text here",
        height=300
    )
    word_count = len(text.split())
    char_count = len(text)
    tokens = int(char_count / 4)
    st.caption(f"Words: {word_count} - Tokens: {tokens}")
    action = st.selectbox(
        "Action",
        [
            "Improve text",
            "Rewrite text",
            "Professional tone",
            "Translate",
            "Organize text"
        ]
    )
    if st.button("Process Text"):
        prompt = f"""
        Action: {action} 
        Apply this to the following text.
        Rules:
        - Keep the same structure
        - Keep approximately the same length
        - Do not summarize
        Text:
        {text}
        """
        response = client.responses.create(
                model="gpt-4.1-mini",
                input=prompt
        )
        result = response.output_text
        st.write(result)
if tool == "Presentation Generator":
    st.header("Presentation Generator")
    topic = st.text_input("Presentation topic")
    user_text = st.text_area(
        "Optional: Paste notes or text for the presentation",
        height=250
    )

    slides = st.slider("Number of slides", 3, 15, 5)
    if st.button("Generate Presentation"):
        prompt = f"""
        Create a presentation outline about {topic}.
        Use the following user notes if helpful:
        {user_text}
        The presentation should have {slides} slides.
        For each slide include:
        - Slide title
        - 3 bullet points
        """
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )
        presentation = response.output_text
        st.session_state.presentation = presentation
    if "presentation" in st.session_state:
            presentation = st.session_state.presentation
            st.write(presentation)
    if st.button("Create PowerPoint"):

        prs = Presentation()
        slide_layout = prs.slide_layouts[1]

        for slide_text in st.session_state.presentation.split("\n\n"):
            slide = prs.slides.add_slide(slide_layout)
            parts = slide_text.split("\n")

            slide.shapes.title.text = parts[0]
            content = slide.placeholders[1]
            content.text = "\n".join(parts[1:])

        prs.save("presentation.pptx")

        with open("presentation.pptx", "rb") as file:
            st.download_button(
                label="Download PowerPoint",
                data=file,
                file_name="presentation.pptx",
            )
if tool == "Pitch Deck Generator":

    st.header("Startup Pitch Deck Generator")

    startup = st.text_input("Startup name")

    problem = st.text_area("Problem your startup solves")

    solution = st.text_area("Your solution")

    market = st.text_area("Target market")

    business_model = st.text_area("Business model")

    funding = st.text_input("Funding needed")

    if st.button("Generate Pitch Deck"):

        prompt = f"""
Create a startup investor pitch deck.

Startup: {startup}

Problem:
{problem}

Solution:
{solution}

Market:
{market}

Business model:
{business_model}

Funding needed:
{funding}

Create slides for:

1. Problem
2. Solution
3. Product
4. Market opportunity
5. Business model
6. Competition
7. Financials
8. Funding ask

Each slide should include:
- Slide title
- 3 bullet points
"""

        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )

        pitch = response.output_text

        st.session_state.pitch = pitch

    if "pitch" in st.session_state:

        st.write(st.session_state.pitch)
if st.button("Create Pitch Deck PowerPoint"):

    prs = Presentation()
    slide_layout = prs.slide_layouts[1]

    for slide_text in st.session_state.pitch.split("\n\n"):
        slide = prs.slides.add_slide(slide_layout)
        parts = slide_text.split("\n")

        slide.shapes.title.text = parts[0]

        content = slide.placeholders[1]
        content.text = "\n".join(parts[1:])

    prs.save("pitch_deck.pptx")

    with open("pitch_deck.pptx", "rb") as file:

        st.download_button(
            label="Download Pitch Deck",
            data=file,
            file_name="pitch_deck.pptx"
        )
if tool == "Business Report":
    st.header("Business Report Generator")
    topic = st.text_input("business topic")
    user_text = st.text_area(
        "Optional: Describe your business idea or paste notes",
        height=250
    )
    if st.text_button("Generate Report"):
        prompt = f"""
        write a professional business report.
        Business topic:
        {topic}
        User idea or notes:
        {user_text}
        Include the following sections:
        - Executive Summary
        - Market Overview
        - Key Trends
        - Opportunities
        - Risks
        - Future Outlook
        - Conclusion
        """
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )
        report = response.output_text
        st.write(report)
import streamlit as st
from pptx import Presentation
st.set_page_config(
    page_title="LongForm AI",
    page_icon="favicon.png",
    layout="wide"
)
from reportlab.pdfgen import canvas
from openai import OpenAI
import os
import base64
from PIL import Image, ImageDraw
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
client = OpenAI()
@st.cache_data
def generate_ai_text(prompt):
    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )
    return response.output_text
st.title("LongForm AI")
st.subheader("AI tools for long-form content")
tool = st.sidebar.selectbox(
    "Choose Tool",
    [
    "Book Generator",
    "Presentation Generator",
    "Pitch Deck Generator",
    "Business Report",
    "Long Text Editor"
    ],
    key="tool_selector"
)
def translate_text(text, language):
    prompt = f"""
    Translate the following text to {language}
    Keep formatting, bullet points and paragraphs.
    IMPORTANT:
    - Do NOT summarize
    - Do NOT shorten the text
    - Keep the same structure
    TEXT:
    {text}
    """
    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt

    )

    return response.output_text
def create_pdf(text, cover_image, filename="book.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    cover = ImageReader(cover_image)
    c.drawImage(cover, 0, 0, width=width, height=height)
    c.showPage()
    c.setFont("Helvetica", 18)
    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, height - 320, "Generated by your AI tool")
    c.showPage()
    c.setFont("Helvetica-Bold", 24)
    c.drawString(200, height - 100, "Table of contents")
    c.setFont("Helvetica", 14)
    y_toc = height - 150
    for line in text.split("\n"):
        if line.startwith("chapter"):
            c.drawString(100, y_toc, line)
            y_toc -= 25
    c.showPage()
    c.setFont("Helvetica-Bold", 24)
    c.drawString(180, height - 80, "AI Generated Book")
    c.setFont("Helvetica", 12)
    y = height - 120
    page = 1
    for line in text.split("\n"):
        c.drawString(40, y, line)
        y -= 20
        if y < 40:
            c.drawString( - 100, 20, f"Page {page}")
            page +=1
            c.showPage()
            c.setFont("Helvetica", 12)
            y = height - 40
            c.save()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
def generate_cover(topic, author):

    prompt = f"Professional book cover for a book about {topic}, author: {author}"

    try:
        response = client.images.generate(
            model="gpt-image-1",
            prompt=prompt,
            size="1024x1024"
        )

        image_base64 = response.data[0].b64_json
        image_bytes = base64.b64decode(image_base64)
        image = Image.open(BytesIO(image_bytes))

        draw = ImageDraw.Draw(image)
        width, height = image.size

        draw.text((width/2 - 150, height - 120), topic.upper(), fill="white")
        draw.text((width/2 - 150, height - 60), author.upper(), fill="white")

        return image

    except Exception as e:
        st.error(f"Error generating cover: {e}")
        return None
if tool == "Book Generator":
    st.header("Book Generator")
    topic = st.text_input("Book topic")
    user_text = st.text_area(
        "Optional: Paste notes or text for the book",
        height=250
    )
    author = st.text_input("Author")
    language = st.selectbox(
        "Translate book to:",
        [   "None",
            "English",
            "Norwegian",
            "Persian",
            "Swedish",
            "Arabic",
            "Urdu",
            "Spanish",
            "Hindi",
            "German",
            "Turkish",
            "Italian",
            "Chinese",
            "French",
            "Japanese"
        ]
    )
    chapters = st.slider("Number of chapters", 1, 10, 3)
    topic = st.text_input("Book topic", key="topic_input")
    author = st.text_input("Author", key="author_input")
    if topic and author:
        cover_image = generate_cover(topic, author)
        st.image(cover_image, caption="AI Generated Book Cover")
        st.markdown(f"**Author:** {author}")
    if st.button("Generate Book"):
        st.session_state.book = {}
        book_summary = ""
        outline_prompt = f"""
        Create a detailed outline for a professional book.
        Book topic:
        {topic}
        User material:
        {user_text}
        The book should contain {chapters} chapters.
        For each chapter provide:
        - Chapter number
        - chapter title
        - short description of what the chapter will cover
        """
        outline_response = client.responses.create(
            model="gpt-4.1-mini",
            input=outline_prompt
        )
        outline = outline_response.output_text
        st.markdown("## Book Outline")
        st.write(outline)
        lang_instruction = ""
        progress = st.progress(0)
        status = st.empty()
        book_container = st.empty()
        book = ""
        for i in range(1, chapters+1):
            status.write(f"Writing chapter {i} of {chapters}...")
            prompt = f"""
            Write Chapter {i} of a professional book about {topic}.
            Book outline:
            {outline}
            Focus only on chapter {i} from the outline. 
            The chapter must be very detailed and contain approximately 2500-3000 words.
            Write long, well-developed paragraphs.
            Book summary so far:
            {book_summary}
            Rules:
            - Wite like a real book author
            - Do NOT mention AI
            - Do NOT ask the reader questions
            - Do NOT say things "let me know if you want more"
            - Use clear headings and explainztions
            - include examples when usefull
            {lang_instruction}
            include explanations and examples.
            """
            try:
                chapter_response = client.responses.create(
                    model="gpt-4.1-mini",
                    input=prompt
                )
                chapter_text = chapter_response.output_text
                st.session_state.book[i] = chapter_text
                summary_prompt = f"""
                Summarize the key ideas of this chapter in 5 sentences.
                Chapter text:
                {chapter_text}
                """
                summary_response = client.responses.create(
                    model="gpt-4.1-mini",
                    input=summary_prompt
                )
                chapter_summary = summary_response.output_text
                book_summary += chapter_summary + "\n"
            except Exception as e:
                st.error(f"Error generating chapter: {e}")
                chapter_text = "Chapter generation failed."
                st.session_state.book[i] = chapter_text
            progress.progress(i / chapters)
            summary_prompt = f"""
            Summarize the key ideas from this chapter in 5 sentences.
            Chapter text:
            {chapter_text}
            """
            summary_response = client.responses.create(
                model="gpt-4.1-mini",
                input=summary_prompt
            )
            chapter_summary = summary_response.output_text
            book_summary += chapter_summary + "\n"
    
        if language != "None":
            lang_instruction = f"write the chapter in {language}."
        else:
            lang_instruction = ""
            book = translate_text(book, language)
        edit_status = st.empty()
        edit_status.write("Editing the full book...")
        edit_prompt = f"""
        You are a professional book editor.
        Improve the following book while keeping the same structure.
        Tasks:
        - Improve writing quality
        - Fix grammar
        - Improve flow between chapters
        - Make the book more professionl
        Book:
        {book}
        """
        edit_response = client.responses.create(
            model="gpt-4.1-mini",
            input=edit_prompt 
        )
        edited_book = edit_response.output_text
        edit_status.success("Book editing complete")
        st.markdown(book)
        if st.button("Create PDF"):
            create_pdf(book, cover_image)

        with open("book.pdf", "rb") as f:
            st.download_button(
                "Download PDF Book",
                data=f,
                file_name="book.pdf",
            )
            for i in sorted(st.session_state.book):
                    st.markdown(f"## Chapter {i}")
                    st.write(st.session_state.book[i])
if tool == "Long Text Editor":
    st.header("Long Text Editor")
    text = st.text_area(
        "Paste your text here",
        height=300
    )
    word_count = len(text.split())
    char_count = len(text)
    tokens = int(char_count / 4)
    st.caption(f"Words: {word_count} - Tokens: {tokens}")
    action = st.selectbox(
        "Action",
        [
            "Improve text",
            "Rewrite text",
            "Professional tone",
            "Translate",
            "Organize text"
        ]
    )
    if st.button("Process Text"):
        prompt = f"""
        Action: {action} 
        Apply this to the following text.
        Rules:
        - Keep the same structure
        - Keep approximately the same length
        - Do not summarize
        Text:
        {text}
        """
        response = client.responses.create(
                model="gpt-4.1-mini",
                input=prompt
        )
        result = response.output_text
        st.write(result)
if tool == "Presentation Generator":
    st.header("Presentation Generator")
    topic = st.text_input("Presentation topic")
    user_text = st.text_area(
        "Optional: Paste notes or text for the presentation",
        height=250
    )

    slides = st.slider("Number of slides", 3, 15, 5)
    if st.button("Generate Presentation"):
        prompt = f"""
        Create a presentation outline about {topic}.
        Use the following user notes if helpful:
        {user_text}
        The presentation should have {slides} slides.
        For each slide include:
        - Slide title
        - 3 bullet points
        """
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )
        presentation = response.output_text
        st.session_state.presentation = presentation
    if "presentation" in st.session_state:
            presentation = st.session_state.presentation
            st.write(presentation)
    if st.button("Create PowerPoint"):

        prs = Presentation()
        slide_layout = prs.slide_layouts[1]

        for slide_text in st.session_state.presentation.split("\n\n"):
            slide = prs.slides.add_slide(slide_layout)
            parts = slide_text.split("\n")

            slide.shapes.title.text = parts[0]
            content = slide.placeholders[1]
            content.text = "\n".join(parts[1:])

        prs.save("presentation.pptx")

        with open("presentation.pptx", "rb") as file:
            st.download_button(
                label="Download PowerPoint",
                data=file,
                file_name="presentation.pptx",
            )
if tool == "Pitch Deck Generator":

    st.header("Startup Pitch Deck Generator")

    startup = st.text_input("Startup name")

    problem = st.text_area("Problem your startup solves")

    solution = st.text_area("Your solution")

    market = st.text_area("Target market")

    business_model = st.text_area("Business model")

    funding = st.text_input("Funding needed")

    if st.button("Generate Pitch Deck"):

        prompt = f"""
Create a startup investor pitch deck.

Startup: {startup}

Problem:
{problem}

Solution:
{solution}

Market:
{market}

Business model:
{business_model}

Funding needed:
{funding}

Create slides for:

1. Problem
2. Solution
3. Product
4. Market opportunity
5. Business model
6. Competition
7. Financials
8. Funding ask

Each slide should include:
- Slide title
- 3 bullet points
"""

        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )

        pitch = response.output_text

        st.session_state.pitch = pitch

    if "pitch" in st.session_state:

        st.write(st.session_state.pitch)
if st.button("Create Pitch Deck PowerPoint"):

    prs = Presentation()
    slide_layout = prs.slide_layouts[1]

    for slide_text in st.session_state.pitch.split("\n\n"):
        slide = prs.slides.add_slide(slide_layout)
        parts = slide_text.split("\n")

        slide.shapes.title.text = parts[0]

        content = slide.placeholders[1]
        content.text = "\n".join(parts[1:])

    prs.save("pitch_deck.pptx")

    with open("pitch_deck.pptx", "rb") as file:

        st.download_button(
            label="Download Pitch Deck",
            data=file,
            file_name="pitch_deck.pptx"
        )
if tool == "Business Report":
    st.header("Business Report Generator")
    topic = st.text_input("business topic")
    user_text = st.text_area(
        "Optional: Describe your business idea or paste notes",
        height=250
    )
    if st.text_button("Generate Report"):
        prompt = f"""
        write a professional business report.
        Business topic:
        {topic}
        User idea or notes:
        {user_text}
        Include the following sections:
        - Executive Summary
        - Market Overview
        - Key Trends
        - Opportunities
        - Risks
        - Future Outlook
        - Conclusion
        """
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=prompt
        )
        report = response.output_text
        st.write(report)